#!/usr/bin/env bash
#
# Q35 x86_64 nix imageless configuration (Requires `nix` and `/nix/store` dir)
#
# Configuration variables
#   NIX_STORE_PATH          Path to the nix store
#   NIX_INIT_REBUILD        Force re-build nix init image. rebuild only when == "yes"
#   NIX_FLAKE_PATH          Path to the flake describing the vm configuration

if [[ -f "${BASEDIR}/contrib/confs/q35_base.conf" ]]; then
  source "${BASEDIR}/contrib/confs/q35_base.conf"
fi

: "${NIX_STORE_PATH:="/nix/store"}"
: "${NIX_INIT_REBUILD:="no"}"
: "${NIX_FLAKE_PATH:="${BASEDIR}/contrib/nix/x86_64-noimgnix-base.nix"}"

_setup_x86_64_q35_noimgnix_base() {
  __setup_q35
}
