#!/usr/bin/env bash
#
# Q35-based boot img vm config
#
# Configuration variables
#   GUEST_BOOT_BASE           Default base boot image to derive images from
#   GUEST_BOOT                Boot image

if [[ -f "${BASEDIR}/contrib/confs/q35_base.conf" ]]; then
  source "${BASEDIR}/contrib/confs/q35_base.conf"
fi

: "${GUEST_BOOT_BASE:="img/base.qcow2"}"
: "${GUEST_BOOT:="$GUEST_BOOT_BASE"}"

_setup_x86_64_q35_base() {
  __setup_q35

  # boot drive
  qemu_drive_add "boot" \
    --file "$GUEST_BOOT" \
    --format "qcow2" \
    --interface "virtio" \
    --discard

}
