name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck

      - name: check
        run: make check

